kafka:
  image: spotify/kafka
  ports:
   - "2181:2181"
   - "9092:9092"
  environment:
   - ADVERTISED_HOST=172.17.0.2
   - ADVERTISED_PORT=9092

confluent:
  image: confluent/schema-registry
  links:
   - kafka:kafka
   - kafka:zookeeper
  ports:
   - "8081:8081"

